"""Public API for the shared RPA runtime."""

from .authorization import (
    AuthorizationAlreadyClaimedError,
    AuthorizationClaim,
    AuthorizationError,
    AuthorizationExpiredError,
    AuthorizationNotGrantedError,
    AuthorizationOperation,
    AuthorizationOutcome,
    AuthorizationRecord,
    AuthorizationRecordInvalidError,
    AuthorizationRecordNotFoundError,
    AuthorizationRevokedError,
    AuthorizationScope,
    AuthorizationScopeMismatchError,
    AuthorizationSession,
    AuthorizationStatus,
    AuthorizationStore,
    AuthorizationStoreUnsafeError,
    AuthorizedBrowserActions,
    BrowserAction,
    BrowserActionNotAuthorizedError,
    BrowserElementNotAuthorizedError,
    BrowserOriginNotAuthorizedError,
    BrowserStepNotAuthorizedError,
    ExternalWriteAlreadyClaimedError,
    ExternalWriteClaim,
    ExternalWriteScope,
    ExternalWriteScopeMismatchError,
    ExternalWriteStatus,
    authorization_scope_digest,
    catalog_lock_digest,
    external_write_payload_digest,
)
from .browser import BrowserActions, ElementSpec, FakeBrowserActions
from .browser_manager import (
    BrowserLaunchSpec,
    BrowserLifecyclePolicy,
    BrowserManager,
    BrowserSession,
    PortLeasePool,
)
from .catalog import (
    CatalogIndex,
    CatalogLock,
    CatalogRef,
    discover_catalog,
    snapshot_catalog,
    verify_catalog_snapshot,
)
from .drission_browser import DrissionBrowserActions
from .elements import (
    ElementCatalogError,
    ElementCheck,
    ElementEntry,
    ExpectedCount,
    check_element_expectations,
    element_specs,
    load_element_catalog,
)
from .diagnostics import exception_diagnostics
from .instructions import Instruction, InstructionRegistry, InstructionSpec
from .verification import (
    Counterexample,
    FakeState,
    CounterexampleContractError,
    CounterexampleResult,
    assert_steps_are_falsifiable,
    check_step_counterexamples,
)

__version__ = "0.8.0"

__all__ = [
    "ElementCatalogError",
    "ElementCheck",
    "ElementEntry",
    "ExpectedCount",
    "check_element_expectations",
    "element_specs",
    "load_element_catalog",
    "Counterexample",
    "FakeState",
    "CounterexampleContractError",
    "CounterexampleResult",
    "assert_steps_are_falsifiable",
    "check_step_counterexamples",
    "AuthorizationAlreadyClaimedError",
    "AuthorizationClaim",
    "AuthorizationError",
    "AuthorizationExpiredError",
    "AuthorizationNotGrantedError",
    "AuthorizationOperation",
    "AuthorizationOutcome",
    "AuthorizationRecord",
    "AuthorizationRecordInvalidError",
    "AuthorizationRecordNotFoundError",
    "AuthorizationRevokedError",
    "AuthorizationScope",
    "AuthorizationScopeMismatchError",
    "AuthorizationSession",
    "AuthorizationStatus",
    "AuthorizationStore",
    "AuthorizationStoreUnsafeError",
    "AuthorizedBrowserActions",
    "BrowserAction",
    "BrowserActionNotAuthorizedError",
    "BrowserActions",
    "BrowserElementNotAuthorizedError",
    "BrowserLaunchSpec",
    "BrowserLifecyclePolicy",
    "BrowserManager",
    "BrowserOriginNotAuthorizedError",
    "BrowserSession",
    "BrowserStepNotAuthorizedError",
    "CatalogIndex",
    "CatalogLock",
    "CatalogRef",
    "DrissionBrowserActions",
    "ElementSpec",
    "ExternalWriteAlreadyClaimedError",
    "ExternalWriteClaim",
    "ExternalWriteScope",
    "ExternalWriteScopeMismatchError",
    "ExternalWriteStatus",
    "FakeBrowserActions",
    "Instruction",
    "InstructionRegistry",
    "InstructionSpec",
    "PortLeasePool",
    "__version__",
    "authorization_scope_digest",
    "catalog_lock_digest",
    "discover_catalog",
    "exception_diagnostics",
    "external_write_payload_digest",
    "snapshot_catalog",
    "verify_catalog_snapshot",
]
